# Site settings
title: Joy Heron - Software Developer
email: joy.heron@innoq.com
description: > # I am a crazy software developer who loves learning and is obsessed with functional programming and trying to find her place in the huge and diverse world of software today.
baseurl: ""
url: "https://joyheron.com" # the base hostname & protocol for your site
twitter_username: iamjoyheron
github_username:  joyheron

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
